from datetime import UTC, datetime
from typing import Any

from sqlalchemy import (
    JSON,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base, BigIntegerPK


def _utc_now() -> datetime:
    return datetime.now(UTC)


class Record(Base):
    """`canonical_key` is generated by deterministic normalization
    (T052) and must never be derived from name alone — two records
    with the same name are not necessarily the same real-world entity;
    prefer the provider's stable ID when available. Uniqueness is
    scoped to the project (not global), per the T000 decision recorded
    in docs/16_MEMORY.md: different projects may legitimately collect
    the same real-world entity as separate records."""

    __tablename__ = "records"
    __table_args__ = (
        Index("ix_records_project_id_collected_at", "project_id", "collected_at"),
        UniqueConstraint("project_id", "canonical_key"),
    )

    id: Mapped[int] = mapped_column(BigIntegerPK, primary_key=True, autoincrement=True)
    project_id: Mapped[int] = mapped_column(
        BigIntegerPK, ForeignKey("projects.id"), nullable=False
    )
    job_id: Mapped[int] = mapped_column(
        BigIntegerPK, ForeignKey("jobs.id"), nullable=False
    )
    provider: Mapped[str] = mapped_column(String(64), nullable=False)
    provider_record_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    canonical_key: Mapped[str] = mapped_column(String(512), nullable=False)
    data_json: Mapped[dict[str, Any]] = mapped_column(JSON, nullable=False)
    collected_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=_utc_now)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=_utc_now, onupdate=_utc_now
    )


class RecordProvenance(Base):
    """Only retain source information the provider terms and
    applicable privacy rules permit (docs/08_SECURITY_COMPLIANCE.md) —
    this table stores whatever the mapper (T043) decides is retainable,
    it doesn't decide that itself."""

    __tablename__ = "record_provenance"

    id: Mapped[int] = mapped_column(BigIntegerPK, primary_key=True, autoincrement=True)
    record_id: Mapped[int] = mapped_column(
        BigIntegerPK, ForeignKey("records.id"), nullable=False
    )
    source_reference: Mapped[str | None] = mapped_column(Text, nullable=True)
    provider_operation: Mapped[str] = mapped_column(String(255), nullable=False)
    collected_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    metadata_json: Mapped[dict[str, Any]] = mapped_column(
        JSON, nullable=False, default=dict
    )
