"""create records and record_provenance tables

Revision ID: 589cf4259331
Revises: 89d4d3766467
Create Date: 2026-08-19 16:57:06.017234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589cf4259331'
down_revision: Union[str, Sequence[str], None] = '89d4d3766467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_record_id', sa.String(length=255), nullable=True),
    sa.Column('canonical_key', sa.String(length=512), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_records_job_id_jobs')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_records_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records')),
    sa.UniqueConstraint('project_id', 'canonical_key', name=op.f('uq_records_project_id'))
    )
    op.create_index('ix_records_project_id_collected_at', 'records', ['project_id', 'collected_at'], unique=False)
    op.create_table('record_provenance',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('provider_operation', sa.String(length=255), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], name=op.f('fk_record_provenance_record_id_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_record_provenance'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_provenance')
    op.drop_index('ix_records_project_id_collected_at', table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
