"""create jobs and job_runs tables

Revision ID: 89d4d3766467
Revises: 88fb5b35267b
Create Date: 2026-08-19 16:53:35.335149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d4d3766467'
down_revision: Union[str, Sequence[str], None] = '88fb5b35267b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('config_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('successful_units', sa.Integer(), nullable=False),
    sa.Column('failed_units', sa.Integer(), nullable=False),
    sa.Column('skipped_units', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['collection_configs.id'], name=op.f('fk_jobs_config_id_collection_configs')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_jobs_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_project_id_status_requested_at', 'jobs', ['project_id', 'status', 'requested_at'], unique=False)
    op.create_index('ix_jobs_status_requested_at', 'jobs', ['status', 'requested_at'], unique=False)
    op.create_table('job_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_runs_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs'))
    )
    op.create_index('ix_job_runs_job_id_status', 'job_runs', ['job_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_runs_job_id_status', table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index('ix_jobs_status_requested_at', table_name='jobs')
    op.drop_index('ix_jobs_project_id_status_requested_at', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
