"""add sessions table and user lockout fields

Revision ID: 9e753afdce70
Revises: 0e4e1aa2581b
Create Date: 2026-08-20 01:33:47.733654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e753afdce70'
down_revision: Union[str, Sequence[str], None] = '0e4e1aa2581b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    # server_default backfills existing rows (any real user table this
    # runs against already has data) — the ORM model's Python-side
    # default=0 only applies to new rows created after this point.
    op.add_column(
        'users',
        sa.Column(
            'failed_login_attempts', sa.Integer(), nullable=False, server_default='0'
        ),
    )
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
